name: '♻️ 리팩토링'
description: '코드 리팩토링을 위한 템플릿입니다'
labels: ['refactor']
body:
  - type: textarea
    id: description
    attributes:
      label: 리팩토링 설명
      description: 어떤 부분을 리팩토링하고 싶으신가요?
      placeholder: 리팩토링이 필요한 이유와 범위를 설명해주세요
    validations:
      required: true

  - type: textarea
    id: current-problems
    attributes:
      label: 현재 문제점
      description: 현재 코드의 문제점은 무엇인가요?
      placeholder: 구체적인 문제점을 설명해주세요

  - type: textarea
    id: improvement
    attributes:
      label: 개선 방안
      description: 어떻게 개선하고 싶으신가요?
      placeholder: 구체적인 개선 방안을 설명해주세요

  - type: checkboxes
    id: terms
    attributes:
      label: 확인사항
      options:
        - label: 이 변경이 기존 기능에 영향을 주지 않습니다
          required: true
